### PR TITLE
Fix speed space chart curves color

### PR DESCRIPTION
**Pull request by flomonster**
## Before

image

## Now

image

### CODE REVIEW

**Review by theocrsb — COMMENTED** [review]
I've selected the `base speed curve` on the mockup and I see an alpha of 0.5 ?

**Comment by flomonster** [comment]
> I've selected the `base speed curve` on the mockup and I see an alpha of 0.5 ?

We have for now only two curves to show. Eco and base, the `0.5` is used for a third curve which is not implemented yet.

**Review by theocrsb — APPROVED** [review]
LGTM and tested

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thank you

**Pull request merged**
