### PR TITLE
Add check commit title action

### PR DESCRIPTION
**Pull request by flomonster**

### CODE REVIEW

**Review by younesschrifi — APPROVED** [review]
LGTM. 
Perhaps you could add an example commit in the error message if you think this is necessary ?

**Comment by flomonster** [comment]
> LGTM. Perhaps you could add an example commit in the error message if you think this is necessary ?

I just copied the script from the osrd repository.

**Review by bloussou — APPROVED** [review]
Thanks ✨

**Review by Yohh — APPROVED** [review]
:muscle:

**Pull request merged**
