### PR TITLE
Fix speed space chart round value to decimal

### LINKED ISSUE #8297: GEV: distance of ticks always display useless `.0` and the cursor distance doesn't show 100 meters
### What happened?

There is a useless 100m precision on the distance ticks because they are rounded at 1km.
However the cursor distance indicator is also rounded at 1km but it should not be.
image

### What did you expect to happen?

The `.0` on the ticks should be removed according to the mockup.
And the cursor distance must be able to display a precision of 100m.
image

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0a34296

### PR DESCRIPTION
**Pull request by flomonster**
Fix the rounding to decimal instead of unit.

image

close https://github.com/OpenRailAssociation/osrd/issues/8297

### CODE REVIEW

**Review by Yohh — COMMENTED** [review]
thanks for this PR

ok for the rounded adjustment

https://github.com/OpenRailAssociation/osrd/issues/8297 can't be closed, `.0` is still possible, we should add a condition to avoid `toFixed()` method if `roundedPosition` doesn't have a decimal

**Comment by flomonster** [comment]
> [OpenRailAssociation/osrd#8297](https://github.com/OpenRailAssociation/osrd/issues/8297) can't be closed, `.0` is still possible, we should add a condition to avoid `toFixed()` method if `roundedPosition` doesn't have a decimal

Good point, I also fixed it (in a second commit).

> [!IMPORTANT]
> This fix expose a new bug. The reticle is slightly offset from the graduations.

image

**Review by Yohh — APPROVED** [review]
LGTM

**Review by Math-R — APPROVED** [review]
lgtm 👍🏻

**Pull request merged**
